config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'terms', to: 'terms#index'
  get 'about', to: 'about#index'
  get 'faq', to: 'common_questions#index'

  resources :users

  resources :tasks do
    resources :comments
  end

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tracker_projects, only:[:show]

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  ROLE = ["Member", "Owner"]

  belongs_to :user
  belongs_to :project

  validates :user, presence: true
  validates_uniqueness_of :user, scope: :project, message: " has already been added to this project"

end

app/controllers/memberships_controller.rb
class MembershipsController < PrivateController

  before_action :set_project
  before_action :set_membership, only: [:update, :destroy]
  before_action :ensure_project_member_or_admin
  before_action :membership_and_owner, only:[:update, :destroy]
  before_action :ensure_admin_or_owner_or_self_user, only: [:destroy]
  before_action :ensure_project_owner_or_admin, only:[:create, :update]


  def index
    @membership = @project.memberships.new
  end

  def create
    @membership = @project.memberships.new(membership_params)
    if @membership.save
      flash[:message] = "#{@membership.user.full_name} was successfully added"
      redirect_to project_memberships_path(@project)
    else
      render :index
    end
  end

  def update
    if @membership.update(membership_params)
      flash[:message] = "#{@membership.user.full_name} was successfully updated"
      redirect_to project_memberships_path
    else
      render :index
    end
  end

  def destroy
    @membership.destroy
    flash[:message] = "#{@membership.user.full_name} was successfully removed"
    if current_user.id == @membership.user_id
      redirect_to projects_path
    else
      redirect_to project_memberships_path(@project)
    end
  end

  private

  def membership_params
    params.require(:membership).permit(:user_id, :project_id, :role)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_membership
    @membership = Membership.where(project_id: @project.id).find(params[:id])
  end

  def membership_and_owner
    if @membership.role == 'Owner' && @project.memberships.where(role: 'Owner').count <= 1
      flash[:error] = "Projects must have at least one owner"
      redirect_to project_memberships_path(@project)
    end
  end

end

app/views/memberships/index.html.haml
.page-header
  %h1= "#{@project.name}: Manager Members"

%ol.breadcrumb
  %li= link_to 'Projects', projects_path
  %li= link_to @project.name, project_path(@project)
  %li.active Membership

- if current_user.owner_admin?(@project)
  .row
    - if @membership.errors.present?
      .form-group
        .col-md-7
          .alert.alert-danger
            %h3
              = pluralized(@membership.errors.count, "error")
              prohibited this form from being saved
            %ul
              -@membership.errors.full_messages.each do |message|
                %li= message

  .row
    = form_for [@project, @membership], html: {class: "form-inline"} do |f|
      .col-md-7
        .well
          = f.collection_select(:user_id, User.all, :id, :full_name, {prompt: "Please select a user..."}, {class:'form-control'})
          = f.collection_select(:role, Membership::ROLE, :to_s, :to_s, {}, {class: 'form-control'})
          = f.submit "Add New Member", class: "btn btn-primary"

.row
  .col-md-7
    %table.table
      %tbody
        - @project.memberships.each do |membership|
          %tr
            - if membership.id
              = form_for [@project, membership], html: {class: "form-inline"} do |f|
                %td= link_to "#{membership.user.full_name}", user_path(membership.user)
                - if current_user.owner_admin?(@project)
                  %td= f.collection_select(:role, Membership::ROLE, :to_s, :to_s, {}, {class: "form-control"})
                  %td= f.submit "Update", class: "btn btn-primary"
                - else
                  %td= membership.role.downcase
                - if current_user.owner_admin?(@project) || current_user.id == membership.user_id
                  - if @project.memberships.where(role:"Owner").count == 1 && membership.role == "Owner"
                    %td You are the last owner
                  - else
                    %td= link_to "", project_membership_path(@project, membership), method: :delete, class: "glyphicon glyphicon-remove"
                - else
                  %td