config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'terms', to: 'terms#index'
  get 'about', to: 'about#index'
  get 'faq', to: 'common_questions#index'

  resources :users

  resources :tasks do
    resources :comments
  end

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tracker_projects, only:[:show]

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/task.rb
class Task < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  belongs_to :project

  validates :description, presence: true

end

app/controllers/tasks_controller.rb
class TasksController < PrivateController

  before_action :set_project
  before_action :set_task, only:[:show, :edit, :destroy]
  before_action :ensure_project_member_or_admin

  def index
    @tasks = @project.tasks
  end

  def show
    @task = Task.find(params[:id])
    @comments = @task.comments.all
    @comment = @task.comments.new
  end

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      flash[:message] = "Task was successfully created"
      redirect_to project_task_path(@project, @task)
    else
      render :new
    end
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def update
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
      flash[:message] = "Task was successfully updated"
      redirect_to project_task_path
    else
      render :edit
    end
  end

  def destroy
    task = @project.tasks.find(params[:id])
    task.destroy
    redirect_to project_tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:description, :complete, :due_date, :project_id)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.where(project_id: @project.id).find(params[:id])
  end

end

app/views/tasks/_form.html.haml
= form_for [@project, @task], html: {class: "form-horizontal"} do |f|

  = render partial: "shared/errors", locals: {object: @task}

  .form-group
    = f.label :description, class: "col-md-2 control-label"
    .col-md-6
      = f.text_field :description, class: "col-md-6 form-control"

  .form-group
    = f.label :due_date, class: "col-md-2 control-label"
    .col-md-3
      = f.date_field :due_date, class: "form-control"

  - unless @task.new_record?
    .form-group
      .col-md-10.col-md-offset-2
        = f.check_box :complete
        = f.label :complete, "Complete"

  .form-group
    .col-md-10.col-md-offset-2
      = f.submit name_of_button, class: "btn btn-primary"
      = link_to 'Cancel', project_tasks_path(@project, @tasks), class: "btn btn-default"

app/views/tasks/edit.html.haml
.page-header
  %h1 Edit Task

%ol.breadcrumb
  %li= link_to 'Projects', projects_path
  %li= link_to @project.name, project_path(@project)
  %li= link_to 'Tasks', project_tasks_path(@project, @tasks)
  %li= link_to @task.description, project_task_path(@project, @task)
  %li.active Edit

= render partial: "form", locals: {name_of_button: "Update Task"}

app/views/tasks/index.html.haml
.page-header
  .pull-right
    = link_to 'New Task', new_project_task_path, class: "btn btn-info"
  %h1= "Tasks for #{@project.name}"

%ol.breadcrumb
  %li= link_to 'Projects', projects_path
  %li= link_to @project.name, project_path(@project)
  %li.active Tasks

%table.table
  %thead
    %tr
      %th Description
      %th Due On
      %th
  %tbody
    - @tasks.each do |task|
      %tr
        %td.col-md-2
          - if task.complete
            %s= link_to task.description, project_task_path(@project, task)
          - else
            = link_to task.description, project_task_path(@project, task)
            %span.badge= task.comments.count
        %td.col-md-2= task.due_date.try(:strftime, "%m/%d/%Y")
        %td.col-md-2.text-right
          = link_to 'Edit', edit_project_task_path(@project, task), class: "btn btn-info"
          = link_to '', project_task_path(@project, task), method: :delete, data: {confirm: "Are you sure?"}, class: "glyphicon glyphicon-remove"

app/views/tasks/new.html.haml
.page-header
  %h1 New Task

%ol.breadcrumb
  %li= link_to 'Projects', projects_path
  %li= link_to @project.name, project_path(@project)
  %li= link_to 'Tasks', project_tasks_path(@project, @tasks)
  %li.active New Task

= render partial: "form", locals: {name_of_button: "Create Task"}

app/views/tasks/show.html.haml
.page-header
  .pull-right
    = link_to 'Edit', edit_project_task_path(@project, @task), class: "btn btn-info"
  %h1
    - if @task.complete
      %s= @task.description
    - else
      = @task.description

%ol.breadcrumb
  %li= link_to 'Projects', projects_path
  %li= link_to @project.name, project_path(@project)
  %li= link_to "Tasks", project_tasks_path(@project)
  %li.active= @task.description

%div
  %p
    %strong Due On:
    - if @task.due_date
      = @task.due_date.strftime("%m/%d/%Y")
    - else
      = @task.due_date

%h3
  %strong Comments

- @comments.each do |comment|
  - if comment.user_id
    .row
      .col-md-3
        = link_to "#{comment.user.full_name}", user_path
        %p.text-muted= "#{time_ago_in_words(comment.created_at)} ago"
      .col-md-9= comment.message

.row
  .col-md-9.col-md-offset-3
    = form_for [@task, @comment] do |f|
      .form-group
        = f.text_area :message, class: "form-control"
      .form-group
        = f.submit "Add Comment", class: "btn btn-primary"