config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'terms', to: 'terms#index'
  get 'about', to: 'about#index'
  get 'faq', to: 'common_questions#index'

  resources :users

  resources :tasks do
    resources :comments
  end

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tracker_projects, only:[:show]

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  validates :name, presence: true


end

app/controllers/projects_controller.rb
class ProjectsController < PrivateController

  before_action :set_project, only:[:show, :edit, :update, :destroy]
  before_action :ensure_project_member_or_admin, except: [:index, :new, :create]
  before_action :ensure_project_owner_or_admin, only: [:edit, :update, :destroy]

  def index
    @projects = current_user.projects
    @projects_admin = Project.all
    tracker_api = TrackerAPI.new
    if current_user.tracker_token?
      @tracker_projects = tracker_api.projects(current_user.tracker_token)
      if @tracker_projects == 403
        flash.now[:error] = "Pivotal Tracker Token is invalid"
      end
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      @project.memberships.create(user: current_user, role: 'Owner')
      flash[:message] = "Project was successfully created"
      redirect_to project_tasks_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:message] = "Project was successfully updated"
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    flash[:message] = "Project was successfully deleted"
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def set_project
    @project = Project.find(params[:id])
  end

end

app/views/projects/_form.html.haml
= form_for @project, html: {class: "form-horizontal"} do |f|

  = render partial: "shared/errors", locals: {object: @project}

  .form-group
    = f.label :name, class: "col-md-2 control-label"
    .col-md-6
      = f.text_field :name, class: "form-control"

  .form-group
    .col-md-10.col-md-offset-2
      = f.submit name_of_button, class: "btn btn-primary"
      = link_to 'Cancel', projects_path(@projects), class: "btn btn-default"
      

app/views/projects/edit.html.haml
.page-header
  %h1 Edit Project

= render partial: "form", locals: {name_of_button: "Update Project"}

%ol.breadcrumb
  %li= link_to 'Projects', projects_path
  %li= link_to @project.name, project_path(@project)
  %li.active Edit
  

app/views/projects/index.html.haml
.page-header
  .pull-right
    = link_to "New Project", new_project_path, class: "btn btn-info"
  %h1 Projects

%table.table
  %thead
    %tr
      %th Name
      %th Tasks
  %tbody
    - if current_user.admin
      - @projects_admin.each do |project|
        %tr
          %td.col-md-6= link_to project.name, project
          %td.col-md-3= link_to project.tasks.count, project_tasks_path(project)
    - else
      -@projects.each do |project|
        %tr
          %td.col-md-6= link_to project.name, project
          %td.col-md-3= link_to project.tasks.count, project_tasks_path(project)

- if current_user.tracker_token
  .page-header
    %h1 Pivotal Tracker Projects

  %table.table
    %thead
      %tr
        %th Name
    %tbody
      -if !(@tracker_projects == 403)
        - @tracker_projects.each do |project|
          %tr
            %td.col-md-6
              = link_to project[:name], tracker_project_path(project[:id], project_name: project[:name])

app/views/projects/new.html.haml
.page-header
  %h1 New Project

= render partial: "form", locals: {name_of_button: "Create Project"}

%ol.breadcrumb
  %li= link_to 'Projects', projects_path
  %li.active New Project

app/views/projects/show.html.haml
.page-header
  - if current_user.owner_admin?(@project)
    .pull-right
      = link_to 'Edit', edit_project_path(@project), class: "btn btn-info"
  %h1= @project.name

%ol.breadcrumb
  %li= link_to 'Projects', projects_path
  %li.active= @project.name

%div
  %p= link_to pluralize(@project.tasks.count, "Task"), project_tasks_path(@project)

%div
  %p= link_to pluralize(@project.memberships.count, "Membership"), project_memberships_path(@project)

- if current_user.owner_admin?(@project)
  .well
    %h3 Delete Project
    %p= "Deleting this project will aslo delete #{pluralize(@project.memberships.count, "membership")}, #{pluralize(@project.tasks.count, "task")} and associated comments."
    = link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"