config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'terms', to: 'terms#index'
  get 'about', to: 'about#index'
  get 'faq', to: 'common_questions#index'

  resources :users

  resources :tasks do
    resources :comments
  end

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tracker_projects, only:[:show]

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title gCamp
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        %div
          - if current_user
            = link_to 'gCamp', projects_path, class: "navbar-brand"
          - else
            = link_to 'gCamp', "/", class:"navbar-brand"
        %ul.nav.navbar-nav.navbar-right
          - if current_user
            = link_to "Sign Out", signout_path, class: "navbar-text pull-right"
            = link_to current_user.full_name, user_path(current_user), class: "navbar-text pull-right"
          - else
            = link_to "Sign In", sign_in_path, class: "navbar-text pull-right"
            = link_to "Sign Up", sign_up_path, class: "navbar-text pull-right"

    .container
      - if flash[:error]
        .alert.alert-danger.text-left= flash[:error]

      - if flash[:message]
        .alert.alert-success.text-left= flash[:message]

      = yield

    %footer.container
      .page-header
      .row
        .col-xs-6
          = link_to "About", "/about"
          |
          = link_to "Terms", "/terms"
          |
          = link_to "FAQ", "/faq"
          - if current_user
            |
            = link_to "Users", "/users"
            |
            = link_to "Projects", "/projects"
        .col-xs-6
          = link_to image_tag("galvanize.png", alt: "Galvanize", class: "links"), "https://coursework.galvanize.com/people/291"
          = link_to image_tag("github.png", alt: "GitHub", class: "links"), "https://github.com/steve970"
          = link_to image_tag("linked_in.jpg", alt: "LinkedIn", class: "links"), "http://www.linkedin.com/in/stevenhirschhorn"

app/views/layouts/private.html.haml
!!!
%html
  %head
    %title gCamp
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        %div= link_to "gCamp", projects_path, class: "navbar-brand"
        %ul.nav.navbar-nav
          %li.dropdown
            = link_to('#', class: 'dropdown-toggle', data:{toggle: 'dropdown'}, role: 'button') do
              Projects
              %span.caret
            %ul.dropdown-menu{role: 'menu'}
              - current_user.projects.each do |project|
                %li= link_to project.name, project_path(project)
              %li.divider
                %li= link_to 'New Project', new_project_path
          %li= link_to 'Users', users_path

        %ul.nav.navbar-nav.navbar-right
          - if current_user
            = link_to "Sign Out", signout_path, class: "navbar-text pull-right"
            = link_to current_user.full_name, user_path(current_user), class: "navbar-text pull-right"
          - else
            = link_to "Sign In", sign_in_path, class: "navbar-text pull-right"
            = link_to "Sign Up", sign_up_path, class: "navbar-text pull-right"

    .container
      - if flash[:error]
        %div.alert.alert-danger.text-left
          = flash[:error]
      - if flash[:message]
        %div.alert.alert-success.text-left
          = flash[:message]

      = yield

    %footer.container
      .page-header
      .row.text-center
        = link_to "Home", "/"
        |
        = link_to "About", "/about"
        |
        = link_to "Terms", "/terms"
        |
        = link_to "FAQ", "/faq"